region              = # e.g., "us-west-2"
vpc_id              = # Use existing VPC ID from AWS console
subnet_ids          = # Use existing subnet IDs from AWS console (one per AZ)
worker_ami          = # Use existing AMI ID from AWS console (must be arm64 to match c7g/c8g)
key_name            = # Use existing EC2 key pair name from AWS console
instance_types      = # List of instance types offered as Spot Fleet overrides (e.g., ["c7g.large", "c7g.xlarge", "c7g.2xlarge", "c8g.large", "c8g.xlarge", "c8g.2xlarge"])
tiff_bucket_name    = # Name of the S3 bucket for TIFF files
source_bucket_name  = # Name of the S3 bucket for source files
queue_name          = # Name of the SQS queue
ecr_repository_name = # Name of the ECR repository